import 'primeflex/primeflex.css';
import './global.css'
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';

import type { Metadata } from "next";
import Navbar from './client/components/Navbar/NavBar';
import Sidebar from './client/components/SideBar/Sidebar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="grid min-h-screen">
          <div className="sm:col-1 hidden sm:block md:col-1">
            <Sidebar />
          </div>
         {children}
        </div>
      </body>
    </html>
  );
}
